=== Nxssie/countryXSL/public/XML_XSL/Norway/default.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.nxssie.com"
           xmlns="https://www.nxssie.com"
           elementFormDefault="qualified">

    <xs:element name="data" type ="data" />

    <xs:complexType name="data">
        <xs:sequence>
            <xs:element name="pop" type ="pop" />
            <xs:element name="gdp" type="gdp" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="pop">
            <xs:sequence>
                <xs:element name="entry" type="entry" maxOccurs="unbounded"/>
            </xs:sequence>
    </xs:complexType>

    <xs:complexType name="gdp">
        <xs:sequence>
            <xs:element name="entry" type="entry" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="entry">
        <xs:sequence>
            <xs:element name="date" type="xs:integer" />
            <xs:element name="indicator" type="xs:string" />
            <xs:element name="country" type="xs:string" />
            <xs:choice>
                <xs:element name="population" type="xs:string" />
                <xs:element name="gdp" type="xs:string" />
            </xs:choice>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Nxssie/countryXSL/public/XML_XSL/Switzerland/swiss_output.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xsi:schemaLocation="https://www.nxssie.com default.xsd" xmlns:wb="http://www.worldbank.org"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.nxssie.com">
    <pop>
        <entry>
            <date>2019</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>NaN</population>
        </entry>
        <entry>
            <date>2018</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>8.516.543,00</population>
        </entry>
        <entry>
            <date>2017</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>8.451.840,00</population>
        </entry>
        <entry>
            <date>2016</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>8.373.338,00</population>
        </entry>
        <entry>
            <date>2015</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>8.282.396,00</population>
        </entry>
        <entry>
            <date>2014</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>8.188.649,00</population>
        </entry>
        <entry>
            <date>2013</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>8.089.346,00</population>
        </entry>
        <entry>
            <date>2012</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.996.861,00</population>
        </entry>
        <entry>
            <date>2011</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.912.398,00</population>
        </entry>
        <entry>
            <date>2010</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.824.909,00</population>
        </entry>
        <entry>
            <date>2009</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.743.831,00</population>
        </entry>
        <entry>
            <date>2008</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.647.675,00</population>
        </entry>
        <entry>
            <date>2007</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.551.117,00</population>
        </entry>
        <entry>
            <date>2006</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.483.934,00</population>
        </entry>
        <entry>
            <date>2005</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.437.115,00</population>
        </entry>
        <entry>
            <date>2004</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.389.625,00</population>
        </entry>
        <entry>
            <date>2003</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.339.001,00</population>
        </entry>
        <entry>
            <date>2002</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.284.753,00</population>
        </entry>
        <entry>
            <date>2001</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.229.854,00</population>
        </entry>
        <entry>
            <date>2000</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.184.250,00</population>
        </entry>
        <entry>
            <date>1999</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.143.991,00</population>
        </entry>
        <entry>
            <date>1998</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.110.001,00</population>
        </entry>
        <entry>
            <date>1997</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.088.906,00</population>
        </entry>
        <entry>
            <date>1996</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.071.850,00</population>
        </entry>
        <entry>
            <date>1995</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>7.040.687,00</population>
        </entry>
        <entry>
            <date>1994</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.993.795,00</population>
        </entry>
        <entry>
            <date>1993</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.938.265,00</population>
        </entry>
        <entry>
            <date>1992</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.875.364,00</population>
        </entry>
        <entry>
            <date>1991</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.799.978,00</population>
        </entry>
        <entry>
            <date>1990</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.715.519,00</population>
        </entry>
        <entry>
            <date>1989</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.646.912,00</population>
        </entry>
        <entry>
            <date>1988</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.593.386,00</population>
        </entry>
        <entry>
            <date>1987</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.545.106,00</population>
        </entry>
        <entry>
            <date>1986</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.504.124,00</population>
        </entry>
        <entry>
            <date>1985</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.470.365,00</population>
        </entry>
        <entry>
            <date>1984</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.441.865,00</population>
        </entry>
        <entry>
            <date>1983</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.418.773,00</population>
        </entry>
        <entry>
            <date>1982</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.391.309,00</population>
        </entry>
        <entry>
            <date>1981</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.354.074,00</population>
        </entry>
        <entry>
            <date>1980</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.319.408,00</population>
        </entry>
        <entry>
            <date>1979</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.294.365,00</population>
        </entry>
        <entry>
            <date>1978</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.281.738,00</population>
        </entry>
        <entry>
            <date>1977</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.281.174,00</population>
        </entry>
        <entry>
            <date>1976</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.302.504,00</population>
        </entry>
        <entry>
            <date>1975</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.338.632,00</population>
        </entry>
        <entry>
            <date>1974</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
            <population>6.341.405,00</population>
        </entry>
        <entry>
            <date>1973</date>
            <indicator>Population, total</indicator>
            <country>Switzerland</country>
